# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'bubbleTest' do
  use_frameworks!

  pod 'Chatto', '= 3.0.0'
pod 'ChattoAdditions', '= 3.0.0' # if you want to use the cells or the input component

end
